{% set name = "zodipy" %}
{% set version = "1.1.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/zodipy-{{ version }}.tar.gz
  sha256: de4b9b17e5d4af1f9c539b5977e06f78202ce09f4aae78743f0bb1c758bf38b7

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python {{ python_min }}
    - poetry-core >=1.0.0
    - pip
  run:
    - python >={{ python_min }}
    - numpy >=1.26.4,<2.0.0
    - astropy >=5.0.1
    - jplephem >=2.17.0,<3.0.0
    - scipy >=1.13.0,<2.0.0

test:
  imports:
    - zodipy
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://github.com/Cosmoglobe/zodipy
  summary: A Python package for zodiacal light simulations
  license: GPL-3.0-or-later
  license_file: LICENSE

extra:
  recipe-maintainers:
    - MetinSa
