{% set name = "zodipy" %}
{% set version = "1.1.2" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/zodipy-{{ version }}.tar.gz
  sha256: fb29c2a1114d214c1c9c14e6ae7966293ffe55493cac6a2d05fa3e4aade67680

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python {{ python_min }}
    - poetry-core >=1.0.0
    - pip
  run:
    - python >={{ python_min }}
    - numpy >=1.26.4,<2.0.0
    - astropy >=5.0.1
    - jplephem >=2.17.0,<3.0.0
    - scipy >=1.13.0,<2.0.0

test:
  imports:
    - zodipy
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://github.com/Cosmoglobe/zodipy
  summary: A Python package for zodiacal light simulations
  license: GPL-3.0-or-later
  license_file: LICENSE

extra:
  recipe-maintainers:
    - MetinSa
